name: Documentation

on:
  pull_request:
  push:
    branches: main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    # Force to use color
    FORCE_COLOR: true
    BROWSER: /usr/bin/firefox
    DISPLAY: :99.0
    
permissions:
  contents: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_bootstrap_theme sphinx_gallery sphinx_rtd_theme myst_parser
      - name: Sphinx build
        id: build-docs
        run: |
          sphinx-build doc _build
      - name: Upload documentation
        if: steps.build-docs.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: DocHTML
          path: doc/_build/html

  deploy_on_main:
    runs-on: ubuntu-latest
    needs: [build_docs]
    if: ${{ contains(fromJSON('["push", "workflow_dispatch", "schedule"]'), github.event_name)}}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: DocHTML
          path: ~/doc/_build/html
      - name: Commit to documentation branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub actions"
          
          git clone git@github.com:hidimstat/hidimstat.github.io.git ~/hidimstat.github.io --depth=1
          cd ~/hidimstat.github.io;
          
          git checkout main

          git remote -v

          git fetch origin
          git reset --hard origin/main

          echo "Deploying dev docs.";
          rm -Rf dev;
          cp -a ~/doc/_build/html dev;
          git add -A;
          git commit -m "Dev docs https://github.com/hidimstat/hidimstat/commit/${{ github.event.head_commit.id }} : ${{ github.event.head_commit.message }}";
          git push origin main;
