name: Deploy GitHub pages

on:
  pull_request:
  push:
    branches: main

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'
    steps:
      - uses: actions/checkout@v2
      - name: Generate HTML docs
        uses: ammaraskar/sphinx-action@master
        env:
          ALLOW: --allow-run-as-root
        with:
          docs-folder: "doc/"
          pre-build-command: |
            apt-get update
            apt-get install -y git libopenmpi-dev openmpi-bin
            apt-get install -y libgl1-mesa-glx
            apt-get install -yqq libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libopengl0
            /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
            pip install -r doc/doc-requirements.txt
            pip install .
            echo "localhost slots=50">hostfile
      - name:  Upload generated HTML as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DocHTML
          path: doc/_build/html/

  deploy_docs:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      build_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: DocHTML
          path: doc/_build/html/
      - name: Commit to documentation branch
        run: |
          git clone --no-checkout --depth 1 https://github.com/${{ github.repository_owner }}/hidimstat.git --branch gh-pages --single-branch gh-pages
          cp -r doc/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "hidimstat@github.com"
          git config --local user.name "hidimstat GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
